### ISSUE TITLE
ich9gen fails with nonsense stderr

### ISSUE THREAD

**Issue by mvhulten** [JaGoLi/Libreboot-X200-Updated#1]
I tried to change the MAC address following the README.  The result on the terminal of `./ich9gen --macaddress ...` is in [this](https://github.com/JaGoLi/Libreboot-X200-Updated/files/5629921/ich9gen-output.log).

I am running OpenBSD-current on a Thinkpad X200.

**Comment by JaGoLi** [comment]
Hello, your issues are caused by you running OpenBSD and not recompiling the ich9gen binary for your OS. The ich9gen binary in the repository is designed for the linux kernel, and will fail when executing on other operating systems such as OpenBSD and FreeBSD. The problem with your ethernet rom is caused by the binary not executing properly and corrupting your image. I will close the second issue, and give you instructions on how to compile the binary on OpenBSD.

**Comment by JaGoLi** [comment]
Ok, so here are the instructions, assuming you are already at the root directory of this git repository:
`cd ./libreboot/resources/utilities/ich9deblob/`
`make clean && make`
`cp ich9gen ../../../.. && cd ../../../..`
And then you can follow the instructions in the readme to change the mac address, and there shouldn't be any errors. Please send feedback if this resolves your issue so I can close the ticket.

**Comment by mvhulten** [comment]
This make sense!  I could use ich9gen to insert the MAC address (amongst other bits I presume), and the network interface is visible again, running the newest Libreboot.  The about 5 seconds long flickering during boot still happens, but that's okay.

Thank you for the quick response and for the whole Libreboot-X200 update!
