### ISSUE TITLE
are these images stable, beta or unstable?

### ISSUE THREAD

**Issue by FrostKnight** [JaGoLi/Libreboot-X200-Updated#3]
I do appreciate you making this updated version, but yeah I am curious.  On an unrelated note, should I spread the word to some people that you are actively fixing the problems that libreboot is stuck with still?

**Comment by JaGoLi** [comment]
These images are intended to be stable, and by comments received from people who have tried them out on real hardware, they do fix bugs present in the latest official images. In order to ensure stability, I built this project using the release version 4.12 of coreboot, which is the stable branch - not the git. The version of GRUB is from the git branch, but that is because the stable version has a known security issue. Coreboot 4.13 has been releaed a few weeks ago, and I am planning to update this repository to keep track of changes in coreboot stable releases.

Given this, definitely spread the word, because it is helping people and fixing security vulnerabilities.

**Comment by FrostKnight** [comment]
This worked like a charm, do you plan to do other libreboot targets and port new targets as well?
Thank you btw for doing this. :)

**Comment by JaGoLi** [comment]
It wouldn't be too difficult for me to port over the project to other devices. Unfortunately, I currently don't own any of them, and would feel uncomfortable releasing something that I can't directly test.

**Comment by FrostKnight** [comment]
okay, thanks! But tell me something, does this version of rom work regardless of keyboard type, language or origin?

As in which country, which keyboard, etc...
