### ISSUE TITLE
paraphrasing, for someone who had this bug,

### ISSUE THREAD

**Issue by FrostKnight** [JaGoLi/Libreboot-X200-Updated#4]
problems i face right now with my x200:
1- a never ending black screen on reboot or at least i waited 2mints smile and keeps the ethernet light turn on and off
2- FN brightness up and down stops working after i decrypt my hdd and start the system i must say that it worked just before openrc started wpa_supplicant then ufw i loose control over brightness
3- my pc have french azerty keyboard and grub on this libreboot doesn't can i fix it?

i will reflash back to the old libreboot release till the brightness problem is fixed cause of my eyes
i also dont have a github account if someone could send this issues to JaGoLi it would be great till i find a way to deal with github

**Comment by JaGoLi** [comment]
1 - this is an issue with coreboot with some ram configurations. I have had this problem, and I think after changing the ram it went away.
2 - coreboot 4.12 has updated ACPI protocols and I have enabled them (ACPI is what controlls brightness). To activate FN + brightness, you need to bind the keys using a hotkey daemon like xbindkeys. To know which keys to bind, open up `xev` and press the keys. This is actually a beeter implementation, because you can change the brightness increments, instead of them being hardcoded in BIOS.
3 - To change the keyboard layout. You can change the keyboard layout by editing the `grub.cfg` in the rom. Simply take the current rom that you are using and run `cbfstool rom_file.rom extract -n grub.cfg -f grub.cfg` and open up the file in your text editor to change the keyboard layout from us to azerty. Then add the file using `cbfstool rom_file.rom add -f grub.cfg -n grub.cfg`.
