### ISSUE TITLE
Blinking power LED while on?

### ISSUE THREAD

**Issue by tslilc** [JaGoLi/Libreboot-X200-Updated#9]
Thanks for your work on this, i wasn't quite sure how to marshal coreboot + grub into building an image!

I appreciate that this may be entirely unrelated to you, and should probably be an upstream question, but just in case you've seen this behaviour before: do you know why the power LED blinks continuously while the device is on? To be sure, it's the one between the battery and HDD indicators. Oddly, while in sleep (which is broken), it's solid. 

This doesn't happen with the coreboot versions from libreboot releases and git. Feel free to close and i could direct this question elsewhere.

**Comment by JaGoLi** [comment]
I don't have enough information in order to troubleshoot the power led issue. Issues like that seem to be highly dependent on individual motherboards. For the sleep issue, if you're running a systemd distribution, you have to set the behaviour in this file: `/etc/systemd/logind.conf`. Sleep seems to be no longer handled by the bios, but rather by the operating system, giving users greater flexibility.

**Comment by tslilc** [comment]
Thanks for looking into this and for the tip!
